# Miscellaneous
google_analytics: UA-31546300-1
favicon: /favicon.ico

# Social
twitter: https://twitter.com/Denisslef
linkedin: https://be.linkedin.com/in/denislefevre
behance: https://www.behance.net/denislefevre
